# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)


platform :ios do
  desc "Build"
  lane :build do
    # add actions here: https://docs.fastlane.tools/actions
    cocoapods(use_bundle_exec: false)
    xcbuild(scheme: "MVDV", workspace: "MVDV.xcworkspace")
    slack(message: "MVDV: built")
  end

  desc "CI Build"
  lane :test do
    # add actions here: https://docs.fastlane.tools/actions
    run_tests(scheme: "MVDVTests")
    slack(message: "MVDV: tested")
  end
end
